# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "GuJin"
description: > # this means to ignore newlines until "email:"
   a programmer

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Gu Jin'
author: 'Gu Jin'
author_image: "/assets/images/logo.jpg"

paginate:	5

url: "http://gujin.tech" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-91077451-1

# social icons and sharing options
# where the icons from : http://fontawesome.io/icons/
social:
  - icon:	github
    url:	https://github.com/GuJin
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:

markdown: kramdown
kramdown:
  input: GFM