# Build settings
plugins:
  - jemoji
  - jekyll-sitemap

exclude:
  - docs

# Site settings
title: "GuJin"
description: >
   Small web tools by GuJin, with a lightweight mother site for current public
   workflows and support pages.

email: gujin@gujin.tech
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Gu Jin'
author: 'Gu Jin'
author_image: "/assets/images/logo.jpg"
lang: "en"

url: "https://gujin.tech" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle:

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics:

# social icons and sharing options
# where the icons from : http://fontawesome.io/icons/
social:
  - icon:	github
    url:	https://github.com/GuJin
    desc:	View GuJin on GitHub
    share_url:
    share_title:
    share_link:

# markdown: kramdown
# kramdown:
#     input: GFM
# highlighter: rouge

timezone: Asia/Shanghai
